spring.application.name=17-03-26
server.port=8081
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=studentdb;encrypt=false
spring.datasource.username=sa
spring.datasource.password=managE321

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect